/**
 * The exact URL, character for character.
 *
 * Every expectation here was checked against a live Adminer 5 first: the URL
 * was generated by the code under test, opened over HTTP against a real
 * PostgreSQL, and the row that came back was the row it was supposed to be.
 * A URL builder tested only against itself is a builder that agrees with its
 * own mistakes.
 */

import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { masked, visible } from '@statescope/core';
import { adminerUrl, MAX_URL_LENGTH } from './adminer.js';
import type { AdminerBinding } from './config.js';

const binding: AdminerBinding = {
  preset: 'adminer-url',
  origin: 'http://127.0.0.1:7442',
  server: '172.17.0.3',
  username: 'postgres',
  grants: [],
};

const location = { database: 'demobank', schema: 'public' };

function urlOf(key: Parameters<typeof adminerUrl>[3]): string {
  const result = adminerUrl(binding, location, 'seats', key);
  assert.ok('url' in result, `expected a URL, got: ${'detail' in result ? result.detail : '?'}`);
  return result.url;
}

describe('the deep link', () => {
  it('carries the four things Adminer keys its session on', () => {
    // Measured: a URL missing any of (driver, server, username, db) renders the
    // login page — and that page echoes the whole request, key value included,
    // into its own recent-links list. A refused handoff discloses as much as a
    // successful one.
    const url = new URL(urlOf([{ name: 'row_no', value: visible('text', '12') }]));
    assert.equal(url.searchParams.get('pgsql'), '172.17.0.3');
    assert.equal(url.searchParams.get('username'), 'postgres');
    assert.equal(url.searchParams.get('db'), 'demobank');
    assert.equal(url.searchParams.get('ns'), 'public');
    assert.equal(url.searchParams.get('select'), 'seats');
  });

  it('numbers a composite key from zero', () => {
    // Verified live: this URL returned row (12, A) and only that row.
    const url = new URL(
      urlOf([
        { name: 'row_no', value: visible('text', '12') },
        { name: 'seat', value: visible('text', 'A') },
      ]),
    );
    assert.equal(url.searchParams.get('where[0][col]'), 'row_no');
    assert.equal(url.searchParams.get('where[0][val]'), '12');
    assert.equal(url.searchParams.get('where[1][col]'), 'seat');
    assert.equal(url.searchParams.get('where[1][val]'), 'A');
  });

  it('matches a NULL with IS NULL and no value at all', () => {
    // The `= NULL` bug wearing a URL. Measured both ways: `op=IS NULL` returned
    // the row whose column really is NULL; `op==` with an empty `val` returned
    // no rows, while looking like a perfectly good link.
    const url = new URL(urlOf([{ name: 'note', value: visible('text', null) }]));
    assert.equal(url.searchParams.get('where[0][op]'), 'IS NULL');
    assert.equal(url.searchParams.has('where[0][val]'), false);
  });

  it('encodes rather than concatenates', () => {
    // Verified live against a row whose value is `o'brien & co`: the link
    // returned that row. An `&` that reached the query unencoded would have
    // started a new parameter.
    const url = new URL(urlOf([{ name: 'who', value: visible('text', "o'brien & co") }]));
    assert.equal(url.searchParams.get('where[0][val]'), "o'brien & co");
  });

  it('never emits Adminer\'s SQL operator', () => {
    // It is in Adminer's vocabulary and its value is spliced into the WHERE
    // clause, so a builder that can reach it is an injection primitive in a
    // URL. The operand type has two members and neither is it.
    const url = urlOf([
      { name: 'who', value: visible('text', "x') OR true --") },
      { name: 'note', value: visible('text', null) },
    ]);
    assert.doesNotMatch(url, /%5Bop%5D=SQL/);
    assert.doesNotMatch(url, /\[op\]=SQL/);
  });
});

describe('what it refuses', () => {
  it('refuses a masked key column, naming it', () => {
    const result = adminerUrl(binding, location, 'people', [
      { name: 'email', value: masked('text') },
    ]);
    assert.ok('detail' in result);
    assert.equal(result.reason, 'target-cannot-address');
    assert.match(result.detail, /`email`/);
    assert.match(result.detail, /masked at capture/);
  });

  it('refuses a key with no columns rather than selecting the whole table', () => {
    const result = adminerUrl(binding, location, 'seats', []);
    assert.ok('detail' in result);
  });

  it('refuses an address longer than a browser will reliably carry', () => {
    // Measured: a 4166-character URL was served correctly by Adminer itself, so
    // the ceiling is not Adminer's — it belongs to the browser and to whatever
    // proxy is in between, neither of which is knowable from here. A URL
    // truncated in transit addresses a different row without saying so.
    const result = adminerUrl(binding, location, 'seats', [
      { name: 'id', value: visible('text', 'a'.repeat(MAX_URL_LENGTH)) },
    ]);
    assert.ok('detail' in result);
    assert.match(result.detail, /characters/);
  });
});
